global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: "junglegaming-processor"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["app:3000"]
        labels:
          app: "wagering-processor"
          environment: "local"
